language: python
python:
  - "3.3"
install:
  - pip install pytest --use-mirrors
script:
  - py.test -vv tests
notifications:
  email:
    recipients:
      - niwi@niwi.be
    on_success: change
    on_failure: change
